services:
  - type: web
    name: missing-link-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run_backend.py
    envVars:
      - key: GROQ_API_KEY
        sync: false
    plan: free
